import pandas as pd
df = pd.read_excel('output/Central-GTSB TX Mini Project TSS PR 20260518.xls')
print('Headers:')
print(df.columns.tolist())
print('\nFirst row data:')
print(df.iloc[0].tolist())
print('\nColumn 1 (Purchasing Area*) values:')
print(df['Purchasing Area*'].tolist())
print('\nColumn 2 (Region*) values:')
print(df['Region*'].tolist())
