{
  "schema_version": "1.0",
  "services": [
    {
      "effective_from": "2024-04-25",
      "effective_to": null,
      "subcontractor": "Allstar",
      "contract_number": "S1MY2024042501WBF1"
    }
  ]
}
